### ISSUE TITLE
Get the number of flashbangs that player carried

### ISSUE THREAD

**Issue by RE-Roger** [saul/demofile#128]
One player could carry 0, 1 or 2 flashbangs. But when I checked the  `player.weapons` it only returned one `weapon` object even if the player did carry two. 
Is it supposed to be like this?
How can I get the number of flashbangs that player carried?
Thanks for your time.

**Comment by master117** [comment]
Same problem exists with demoparser, check the ammo of the flashbang instead of the amount. 2 Flashbangs is one with 2 charges. Took me half a month to find.

**Comment by RE-Roger** [comment]
@master117 Thanks for being a big help. I did check demoinfo's related issues.
But still, I cannot find any accessors about ammo in this library. 
Should I implement the ammo accessor myself? 
If so, could you give me some guidance on how to do that?
I am pretty new to this project.

**Comment by saul** [comment]
I can get an update out this evening that gives access to clip count and reserve count.

**Comment by RE-Roger** [comment]
@saul You have my gratitude, I am looking forward to this enhancement.

**Comment by mdolr** [comment]
Hello, I would like to know if any progress has been made on this or if a temporary solution exists with this library ?

**Comment by saul** [comment]
So you want to index into the player’s m_iAmmo prop table with the offset specified in the grenade’s m_iPrimaryAmmoType. I do have a change locally which does this but I was struggling to get it to work correctly.

Let me know how you get on.

**Comment by mdolr** [comment]
Hey, thanks for the quick answer, I'm working with demos from the major, I've isolated a few moment so that I could compare with the match on youtube and it seems to work perfectly fine !

**Comment by mdolr** [comment]
Also while I'm at it, it seems like :
`molotov_detonate` never emits anything
`grenade_bounce` never emits anything
`grenade_thrown` never emits anything and grenade throws are emitted through `weapon_fire` (I'd like to get the player position (or at least player's name) when throwing the nade if possible so that I can calculate the success rate of a player throwing flashes)

**Comment by saul** [comment]
See https://github.com/saul/demofile/issues/94 for your above comment - please raise a separate issue if you have other questions.

**Comment by saul** [comment]
Fixed in v1.3.0 - see https://saul.github.io/demofile/classes/_entities_weapon_.weapon.html

Added:

- Weapon#clipAmmo
- Weapon#reserveAmmo
- Weapon#ownerAmmo

For number of flashbangs a player is carrying, you want to get the flashbang weapon for that player (see `Player#weapons`), and then check the `ownerAmmo` property.
