### ISSUE TITLE
add to player m_iCashSpentThisRound and m_iTotalCashSpent 

### ISSUE THREAD

**Issue by mavrick** [saul/demofile#41]
G'day mate,

**Reference:** https://github.com/L33T/CSGO-Reflection/blob/master/DT_CSPlayerResource.txt

Is it possible to add ``m_iCashSpentThisRound `` and ``m_iTotalCashSpent `` to the ``Player `` entity?

I see the is ``account()`` that returns ``m_iAccount``

Would adding these be similar to the the ``mvps()`` getter?

```javascript
get mvps() {
    let pr = this._demo.entities.getSingleton('DT_CSPlayerResource');
    let mvps = pr.props['m_iMVPs'];
    return mvps[Object.keys(mvps)[this.index]];
  }
```

Cheers

**Comment by saul** [comment]
Sure thing - feel free to open a pull request!

**Comment by necuk** [comment]
this would be great because now I had to calculate money spent based on equipment_start, equipment_freezetime_end and equipment_buytime_end. with that feature it would take 2 rows instead of dozens

@saul, kindly remind you about another issue that caused a massive discussion https://github.com/saul/demofile/pull/34

I am still using my quick patch and didnt notice any problem. However you mentioned you know a better way to bypass the problem. If you tell me what is the issue you want to count for I could try to propose another solution.

Credits for a very useful library

**Comment by saul** [comment]
@necuk can you open a new issue please with an example demo file that's causing the issue?

**Comment by saul** [comment]
0.4.10 released with these features

**Comment by mavrick** [comment]
Thanks @saul - Once I've gone through all the reflection files I will send through a PR with some more ;) I see StatsHelix has a few more so will make note of them as well.

Cheers mate
